[project]
name = "sre-bot"
version = "0.1.0"
description = "SRE Agent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.3.2",
    "langgraph>=0.4.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
